services:
  app:
    build: .
    ports:
      - "3000:3000"  # Frontend
      - "5000:5000"  # Backend API
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/frontend/node_modules
    environment:
      - NODE_ENV=production
    restart: unless-stopped 